
rails:
  config:
    sensitive_data_detection:
      sensitive_data_protection_endpoint: "http://moderation.tmryk.com:8006"
      
      input:
        entities:
          # Global entities
          - CREDIT_CARD
          - CRYPTO
          - EMAIL_ADDRESS
          - IBAN_CODE
          - IP_ADDRESS
          - NRP
          - LOCATION
          - PERSON
          - PHONE_NUMBER
          - MEDICAL_LICENSE
          - URL
          # US-specific entities
          - US_BANK_NUMBER
          - US_DRIVER_LICENSE
          - US_ITIN
          - US_PASSPORT
          - US_SSN
      output:
        entities:
          # Global entities
          - CREDIT_CARD
          - CRYPTO
          - DATE_TIME
          - EMAIL_ADDRESS
          - IBAN_CODE
          - IP_ADDRESS
          - NRP
          - LOCATION
          - PERSON
          - PHONE_NUMBER
          - MEDICAL_LICENSE
          - URL
          # US-specific entities
          - US_BANK_NUMBER
          - US_DRIVER_LICENSE
          - US_ITIN
          - US_PASSPORT
          - US_SSN
      retrieval:
        entities:
          # Global entities
          - CREDIT_CARD
          - CRYPTO
          - DATE_TIME
          - EMAIL_ADDRESS
          - IBAN_CODE
          - IP_ADDRESS
          - NRP
          - LOCATION
          - PERSON
          - PHONE_NUMBER
          - MEDICAL_LICENSE
          - URL
          # US-specific entities
          - US_BANK_NUMBER
          - US_DRIVER_LICENSE
          - US_ITIN
          - US_PASSPORT
          - US_SSN

  input:
    flows:
      - mask sensitive data on input
  output:
    flows:
      - mask sensitive data on output
  retrieval:
    flows:
      - mask sensitive data on retrieval
