# Please update this policy from the "Add/Update" policy section.
# You can select a model and engine you would like to use and please add your API key for the engine you select.
# Also you can click on "Jailbreak Detection" checkbox and activate the Jailbreak detection capabilities
#
# ## Warning:
# Please back up the current configuration file in order to prevent data loss when you update the policy.

rails:
  input:
    flows:
      - aegis guard check input
      
  output:
    flows:
      - aegis guard check output
  
  dialog:
    single_call:
      enabled: True
  
  config:
    jailbreak_detection:
      #You should have your own instance running for jailbeak and safety
      server_endpoint: "https://jailbreak.tmryk.com/heuristics"
      lp_threshold: 89.79
      ps_ppl_threshold: 1845.65

    safety_check:
      server_endpoint: "http://moderation.tmryk.com:8020/safety-check"
    spell_check:
      server_endpoint: "http://moderation.tmryk.com:8004/spell-check"
    bias_check:
      server_endpoint: "http://moderation.tmryk.com:8004/bias-check"