# Please update this policy from the "Add/Update" policy section.
# You can select a model and engine you would like to use and please add your API key for the engine you select.
# Also you can click on "Jailbreak Detection" checkbox and activate the Jailbreak detection capabilities
#
# ## Warning:
# Please back up the current configuration file in order to prevent data loss when you update the policy.

instructions:
  - type: general
    content: |
      Below is a conversation between a user and a bot called the Tumeryk Bot.
      The bot is designed to answer employee questions about the Tumeryk Company.
      The bot is knowledgeable about the employee handbook and company policies.
      If the bot does not know the answer to a question, it truthfully says it does not know.

sample_conversation: |
  user "Hi there. Can you help me with some questions I have about the company?"
    express greeting and ask for assistance
  bot express greeting and confirm and offer assistance
    "Hi there! I'm here to help answer any questions you may have about the Tumeryk Company. What would you like to know?"
  user "What's the company policy on paid time off?"
    ask question about benefits
  bot respond to question about benefits
    "The Tumeryk Company provides eligible employees with up to two weeks of paid vacation time per year, as well as five paid sick days per year. Please refer to the employee handbook for more information."

rails:
  input:
    flows:
      - jailbreak detection heuristics
      - spell check
      - check bias input
      - aegis guard check input
      
      
  output:
    flows:
      - alignscore check facts
      - aegis guard check output
      - check bias output
  
  dialog:
    single_call:
      enabled: True
  
  config:
    jailbreak_detection:
      #You should have your own instance running for jailbeak and safety
      server_endpoint: "https://jailbreak.tmryk.com/heuristics"
      lp_threshold: 89.79
      ps_ppl_threshold: 1845.65

    safety_check:
      server_endpoint: "http://moderation.tmryk.com:8020/safety-check"
    spell_check:
      server_endpoint: "http://moderation.tmryk.com:8004/spell-check"
    bias_check:
      server_endpoint: "http://moderation.tmryk.com:8004/bias-check"
    fact_checking:
      parameters:
        endpoint: "http://100.21.230.138/alignscore_base"
